version: "2.4"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb
    healthcheck:
      test: awslocal dynamodb list-tables
      interval: 3s
      timeout: 10s
      retries: 5
    volumes:
      - ./localstack-data:/tmp/localstack
      - ./localstack-bin:/docker-entrypoint-initaws.d

  site:
    build:
      context: site
      target: local
    ports:
      - '3000:3000'

  api:
    build:
      context: api
      target: local
    ports:
      - '3001:3000'
    
    # GUITAR_TABLE needs to match localstack-bin/guitar-table.json
    environment:
      - LOCALSTACK_ENDPOINT=http://172.17.0.1:4566
      - AWS_ACCESS_KEY_ID=AKIAEXAMPLE123
      - AWS_SECRET_ACCESS_KEY=AKIA123
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - ENV=dev
      - REGION=us-east-1
      - GUITAR_TABLE=guitar-table
