name: Build and publish manifest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull docker base image
        run: docker pull node:16-buster
        shell: pwsh

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install zx
        run: npm i -g zx

      - name: Run build script
        run: zx ./Build.mjs

      - name: Build containers in parallel
        run: docker-compose -f Build.yml build --parallel
        shell: pwsh

      - name: Copy built artifacts from containers
        run: docker-compose -f Build.yml up
        shell: pwsh

      - name: Publish
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT: ${{ secrets.PIPELINE_AWS_ACCOUNT }}
        run: docker-compose -f Publish.yml up --build --exit-code-from run
        shell: pwsh
